# Generated by Django 4.1 on 2022-08-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='email',
            field=models.EmailField(default='sample@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
